export const BaseApiHeaders = {
  /** The content type accepted */
  Accept: 'accept',
  AcceptCH: 'Accept-CH',
  AcceptCharset: 'Accept-Charset',
  AcceptEncoding: 'Accept-Encoding',
  AcceptLanguage: 'Accept-Language',
  AcceptPatch: 'Accept-Patch',
  AcceptPost: 'Accept-Post',
  AcceptRanges: 'Accept-Ranges',
  AccessControlAllowCredentials: 'Access-Control-Allow-Credentials',
  AccessControlAllowHeaders: 'Access-Control-Allow-Headers',
  AccessControlAllowMethods: 'Access-Control-Allow-Methods',
  /** Whether the response can be shared with requesting code from the given origin. */
  AccessControlAllowOrigin: 'Access-Control-Allow-Origin',
  AccessControlExposeHeaders: 'Access-Control-Expose-Headers',
  AccessControlMaxAge: 'Access-Control-Max-Age',
  AccessControlRequestHeaders: 'Access-Control-Request-Headers',
  AccessControlRequestMethod: 'Access-Control-Request-Method',
  Age: 'Age',
  Allow: 'Allow',
  /** The authorization token bearer */
  Authorization: 'Authorization',
  CacheControl: 'Cache-Control',
  ClearSiteData: 'Clear-Site-Data',
  Connection: 'Connection',
  ContentDisposition: 'Content-Disposition',
  ContentEncoding: 'Content-Encoding',
  ContentLanguage: 'Content-Language',
  ContentLength: 'Content-Length',
  ContentLocation: 'Content-Location',
  ContentRange: 'Content-Range',
  ContentSecurityPolicy: 'Content-Security-Policy',
  ContentSecurityPolicyReportOnly: 'Content-Security-Policy-Report-Only',
  ContentType: 'Content-Type',
  Cookie: 'Cookie',
  CrossOriginEmbedderPolicy: 'Cross-Origin-Embedder-Policy',
  CrossOriginOpenerPolicy: 'Cross-Origin-Opener-Policy',
  CrossOriginResourcePolicy: 'Cross-Origin-Resource-Policy',
  Date: 'Date',
  DeviceMemory: 'Device-Memory',
  Expect: 'Expect',
  Expires: 'Expires',
  Forwarded: 'Forwarded',
  From: 'From',
  Host: 'Host',
  KeepAlive: 'Keep-Alive',
  LastModified: 'Last-Modified',
  Link: 'Link',
  Location: 'Location',
  MaxForwards: 'Max-Forwards',
  Origin: 'Origin',
  PermissionsPolicy: 'Permissions-Policy',
  ProxyAuthenticate: 'Proxy-Authenticate',
  ProxyAuthorization: 'Proxy-Authorization',
  Range: 'Range',
  Referer: 'Referer',
  ReferrerPolicy: 'Referrer-Policy',
  ReportingEndpoints: 'Reporting-Endpoints',
  RetryAfter: 'Retry-After',
  Server: 'Server',
  ServerTiming: 'Server-Timing',
  ServiceWorkerNavigationPreload: 'Service-Worker-Navigation-Preload',
  SetCookie: 'Set-Cookie',
  SourceMap: 'SourceMap',
  StrictTransportSecurity: 'Strict-Transport-Security',
  TimingAllowOrigin: 'Timing-Allow-Origin',
  Trailer: 'Trailer',
  TransferEncoding: 'Transfer-Encoding',
  Upgrade: 'Upgrade',
  UpgradeInsecureRequests: 'Upgrade-Insecure-Requests',
  /** The user agent of the consumer client */
  UserAgent: 'User-Agent',
} as const;

export const BaseHeaderContentType = {
  OctetStream: 'application/octet-stream',
  Text: 'text/plain',
  Css: 'text/css',
  Html: 'text/html',
  Javascript: 'text/javascript',
  Apng: 'image/apng',
  Avif: 'image/avif',
  Gif: 'image/gif',
  Jpeg: 'image/jpeg',
  Png: 'image/png',
  Svg: 'image/svg+xml',
  Webp: 'image/webp',
  FormData: 'multipart/form-data',
  ByteRanges: 'multipart/byteranges',
  Json: 'application/json',
  Xml: 'application/xml',
  FormUrlEncoded: 'application/x-www-form-urlencoded',
} as const;
